# Generated by Django 4.1.10 on 2023-07-21 02:22

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import mws_main.models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('repo_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, verbose_name='repository name')),
                ('repo_addr', models.CharField(max_length=25, verbose_name='repository address')),
                ('url', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('current_agree', djongo.models.fields.EmbeddedField(model_container=mws_main.models.SubsAgreement)),
                ('old_agrees', djongo.models.fields.ArrayField(model_container=mws_main.models.SubsAgreement)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serv_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, verbose_name='service name')),
                ('last_version', mws_main.models.VersionField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{1,2}\\.\\d{1,2}(.\\d{1,2})?$', flags=re.RegexFlag['ASCII'])])),
                ('package', models.FileField(upload_to='', verbose_name=mws_main.models.Service.repo_dir_path)),
                ('package_type', models.CharField(choices=[('APK', 'Android Package (APK)'), ('IPA', 'iOS App (IPA)')], max_length=3)),
                ('size', models.PositiveIntegerField()),
                ('n_downloads', models.PositiveIntegerField(verbose_name='number of downloads')),
                ('descrp', models.TextField(verbose_name='description')),
                ('categories', djongo.models.fields.JSONField()),
                ('version_history', djongo.models.fields.ArrayField(model_container=mws_main.models.VersionEntry)),
                ('repo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mws_main.repo')),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('dev_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('repo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mws_main.repo')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('client_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('repo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mws_main.repo')),
                ('services_acq', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='mws_main.service')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
