# Generated by Django 4.2.5 on 2023-09-16 02:45

from django.db import migrations, models
import mws_main.models


class Migration(migrations.Migration):

    dependencies = [
        ('mws_main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreMetadata',
        ),
        migrations.AlterField(
            model_name='package',
            name='package_file',
            field=models.FileField(max_length=150, upload_to=mws_main.models.store_dir_path, verbose_name='package file'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(help_text='Copied from the first package icon.', max_length=150, upload_to=mws_main.models.image_dir_path),
        ),
    ]
