# Generated by Django 4.2.4 on 2023-08-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mws_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('view_admin_client', 'Can view detailed information of a client')]},
        ),
        migrations.AlterModelOptions(
            name='developer',
            options={'permissions': [('view_admin_developer', 'Can view detailed information of a developer')]},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'permissions': [('view_admin_service', 'Can view detailed information of a service')]},
        ),
        migrations.RemoveField(
            model_name='service',
            name='os_version',
        ),
        migrations.AlterField(
            model_name='service',
            name='date_uploaded',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='descrp',
            field=models.TextField(blank=True, help_text='1000 characters max. Markdown markup available', max_length=1000, verbose_name='description'),
        ),
    ]
