# Generated by Django 4.2.4 on 2023-08-29 01:44

from django.db import migrations, models
import djongo.models.fields
import mws_main.models


class Migration(migrations.Migration):

    dependencies = [
        ('mws_main', '0002_alter_client_options_alter_developer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='date_uploaded',
        ),
        migrations.RemoveField(
            model_name='service',
            name='descrp',
        ),
        migrations.RemoveField(
            model_name='service',
            name='last_version',
        ),
        migrations.RemoveField(
            model_name='service',
            name='n_downloads',
        ),
        migrations.RemoveField(
            model_name='service',
            name='os_name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='package',
        ),
        migrations.RemoveField(
            model_name='service',
            name='package_type',
        ),
        migrations.RemoveField(
            model_name='service',
            name='version_history',
        ),
        migrations.AddField(
            model_name='service',
            name='packages',
            field=djongo.models.fields.ArrayField(default=[], model_container=mws_main.models.Package),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(help_text='Service icon', upload_to=mws_main.models.image_dir_path),
        ),
    ]
