# Generated by Django 4.2.5 on 2023-09-16 09:22

from django.db import migrations, models
import mws_main.models


class Migration(migrations.Migration):

    dependencies = [
        ('mws_main', '0002_delete_storemetadata_alter_package_package_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(help_text='Copied from the first package icon.', upload_to=mws_main.models.image_dir_path),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=50, verbose_name='service name'),
        ),
    ]
