# Generated by Django 4.2.4 on 2023-08-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mws_main', '0003_remove_service_date_uploaded_remove_service_descrp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='descrp',
            field=models.TextField(default='', verbose_name='description'),
            preserve_default=False,
        ),
    ]
