# Generated by Django 4.2.5 on 2023-09-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mws_main', '0003_alter_service_icon_alter_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=60, verbose_name='package name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=25, verbose_name='service name'),
        ),
    ]
