# Generated by Django 4.2.4 on 2023-09-01 17:22

from django.db import migrations, models
import djongo.models.fields
import mws_main.models


class Migration(migrations.Migration):

    dependencies = [
        ('mws_main', '0004_service_descrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='autoid_for_packages',
            field=models.BigIntegerField(default=6, help_text='Last id used to create a package within the service.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='packages',
            field=djongo.models.fields.ArrayField(default=[], help_text='Concrete software packages contained by the service.', model_container=mws_main.models.Package),
        ),
    ]
