# Generated by Django 4.2.4 on 2023-09-02 16:01

from django.db import migrations, models
import django.utils.timezone
import mws_main.models


class Migration(migrations.Migration):

    dependencies = [
        ('mws_main', '0005_service_autoid_for_packages_alter_service_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='date_published',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date when the service was firstly published.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='n_downloads',
            field=models.PositiveIntegerField(default=0, verbose_name='number of downloads'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(help_text='Copied from the first package icon.', upload_to=mws_main.models.image_dir_path),
        ),
    ]
