# Generated by Django 4.2.4 on 2023-09-03 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mws_main', '0006_service_date_published_service_n_downloads_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='date_published',
        ),
        migrations.AddField(
            model_name='service',
            name='brief_descrp',
            field=models.TextField(default='', verbose_name='brief description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='datetime_published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date and time when the service was firstly published.'),
            preserve_default=False,
        ),
    ]
