# Generated by Django 4.2.3 on 2023-08-08 14:27

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import tenants.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSubsAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Agreement name', max_length=25, unique=True)),
                ('plans', djongo.models.fields.ArrayField(help_text='Show the maximum usage for a resource that can be used', model_container=tenants.models.IResourcePlan)),
                ('duration', models.DurationField(help_text='Units in days')),
            ],
            options={
                'verbose_name': 'available subscription agreement',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='repository name')),
                ('repo_addr', models.CharField(help_text='Address to the hosted tenant store.', max_length=25, verbose_name='repository address')),
            ],
        ),
        migrations.CreateModel(
            name='TenantAdmin',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
