# Generated by Django 5.0.4 on 2024-04-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='store name')),
                ('subdomain_prefix', models.CharField(help_text='Subdomain address to the tenant store.', max_length=25, unique=True)),
                ('db_name', models.CharField(max_length=25, unique=True)),
                ('metadata', models.JSONField()),
            ],
        ),
    ]
