# Generated by Django 5.0.4 on 2024-04-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_remove_tenant_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(default='admin@test.com', max_length=254),
            preserve_default=False,
        ),
    ]
