# Generated by Django 5.0.6 on 2024-05-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='db_host',
            field=models.CharField(default='t', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='db_password',
            field=models.CharField(default='t', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='db_port',
            field=models.CharField(default='t', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='db_user',
            field=models.CharField(default='t', max_length=30),
            preserve_default=False,
        ),
    ]
