# Generated by Django 4.2.4 on 2023-09-13 11:07

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreMetadata',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('main_theme_color', models.CharField(choices=[('purple', 'Purple'), ('red', 'Red'), ('blue', 'Blue'), ('yellow', 'Yellow')], default='purple', help_text='Please pick a color for the main theme.', max_length=10)),
                ('footer_col1_text', models.CharField(max_length=50, null=True)),
                ('footer_col1_url', models.URLField(null=True)),
                ('footer_col2_text', models.CharField(max_length=50, null=True)),
                ('footer_col2_url', models.URLField(null=True)),
                ('footer_col3_text', models.CharField(max_length=50, null=True)),
                ('footer_col3_url', models.URLField(null=True)),
                ('footer_col4_text', models.CharField(max_length=50, null=True)),
                ('footer_col4_url', models.URLField(null=True)),
            ],
        ),
    ]
